"""init schema

Revision ID: f6a2072f5546
Revises: e761509fa24a
Create Date: 2025-10-28 21:40:44.469665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6a2072f5546'
down_revision: Union[str, Sequence[str], None] = 'e761509fa24a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('body_md', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_table('summaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('start_ts', sa.DateTime(), nullable=False),
    sa.Column('end_ts', sa.DateTime(), nullable=False),
    sa.Column('summary_md', sa.Text(), nullable=False),
    sa.Column('topics_json', sa.JSON(), nullable=True),
    sa.Column('mood_trend_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('note_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('start', sa.Integer(), nullable=True),
    sa.Column('end', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_note_id'), 'entities', ['note_id'], unique=False)
    op.create_table('links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('src_note_id', sa.String(), nullable=False),
    sa.Column('dst_note_id', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['dst_note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['src_note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('src_note_id', 'dst_note_id', name='uq_links_src_dst')
    )
    op.create_index(op.f('ix_links_dst_note_id'), 'links', ['dst_note_id'], unique=False)
    op.create_index(op.f('ix_links_src_note_id'), 'links', ['src_note_id'], unique=False)
    op.create_table('meta',
    sa.Column('note_id', sa.String(), nullable=False),
    sa.Column('sentiment', sa.Float(), nullable=True),
    sa.Column('mood', sa.String(), nullable=True),
    sa.Column('tone', sa.String(), nullable=True),
    sa.Column('reading_time_sec', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('note_id')
    )
    op.create_table('tags',
    sa.Column('note_id', sa.String(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('note_id', 'tag')
    )
    op.create_index('ix_tags_tag', 'tags', ['tag'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tags_tag', table_name='tags')
    op.drop_table('tags')
    op.drop_table('meta')
    op.drop_index(op.f('ix_links_src_note_id'), table_name='links')
    op.drop_index(op.f('ix_links_dst_note_id'), table_name='links')
    op.drop_table('links')
    op.drop_index(op.f('ix_entities_note_id'), table_name='entities')
    op.drop_table('entities')
    op.drop_table('summaries')
    op.drop_table('notes')
    # ### end Alembic commands ###
